-- Auto Generated (Do not modify) 48006B3610C988080A2E3ADE3C34B8DA6DC2E1CF51512CB2BCFFC4AB99AE5EAC
CREATE   VIEW dbo.INT_DIM_WEATHER AS
WITH 
    SOURCE AS (
        SELECT * FROM dbo.STG_WEATHER_NYC
    ),

    STG_DIM AS (
        SELECT
            TIME_READABLE,
            CAST(TIME_READABLE AS DATE) AS DATE_READABLE,
            COUNTRY,
            CITY_NAME,
            WEATHER_MAIN,
            UPPER(SUBSTRING(WEATHER_DESCRIPTION, 1, 1)) + SUBSTRING(WEATHER_DESCRIPTION, 2, LEN(WEATHER_DESCRIPTION)) AS WEATHER_DETAIL,
            TEMPERATURE - 273.15 AS TEMPERATURE_CELSIUS,
            HUMIDITY,
            WIND_SPEED,
            CAST(CITY_LATITUDE AS DECIMAL(9,6)) AS CITY_LATITUDE,
            CAST(CITY_LONGITUDE AS DECIMAL(9,6)) AS CITY_LONGITUDE,
            ROUND(CAST(CITY_LATITUDE AS DECIMAL(9,6)), 0) AS CITY_LAT_BUCKET,
            ROUND(CAST(CITY_LONGITUDE AS DECIMAL(9,6)), 0) AS CITY_LON_BUCKET,
            CITY_LOCATION,
            CITY_LOCATION AS CITY_LOCATION_WKT,
            TEMPERATURE AS TEMPERATURE_KELVIN,
            PRESSURE,
            WIND_DEG,
            CITY_ID,
            CITY_FINDNAME,
            METADATA_FILE_LAST_MODIFIED AS UPDATED_AT 
        FROM SOURCE
    )

SELECT * FROM STG_DIM;